### ISSUE TITLE
updates and over to you!

### ISSUE THREAD

**Issue by jessimk** [UBC-MDS/DSCI-522-Jes-Alex#54]
Hey @ehhope !

A few things:
- I tested out your latest awesome script and added the blurb header. Also tested out all our scripts in order to make sure all outputs and inputs are working beautifully-- 🙌

- I updated our report with a section to include our discussion about what we could try, if we had more time. Take a look and let me know if I captured our thoughts alright and as always, feel free to edit.

 - I updated our readme with links to all the things.

**If you can, take a look at our repo and when you're happy with it can you set up our next release?**

_(...if you're tight for time-- no worries, I can set up the release. Just let me know once you're done with review and edits)._

**Comment by ehhope** [comment]
@jessimk 

Hey, that all sounds great! I've gone through the final report and added some things, as well as ran the scripts on my side and it all checks out! Awesome!

I've setup the next release as well (2.0)
